# https://github.com/brandtbucher/travis-python-matrix

# CPython 3.8.1 / CPython 3.7.3 / CPython 3.6.8
# Ubuntu 16.04 (Xenial Xerus) / Windows 10 / macOS 10.14 (Mojave)

# Builds the following wheels:
# - cp38-cp38m-linux-x86-64.whl -> cp38-cp38m-manylinux1-x86-64.whl
# - cp37-cp37m-linux-x86-64.whl -> cp37-cp37m-manylinux1-x86-64.whl
# - cp36-cp36m-linux-x86-64.whl -> cp36-cp36m-manylinux1-x86-64.whl
# - cp38-cp38m-win_amd64.whl
# - cp37-cp37m-win_amd64.whl
# - cp36-cp36m-win_amd64.whl
# - cp38-cp38m-win32.whl
# - cp37-cp37m-win32.whl
# - cp36-cp36m-win32.whl
# - cp38-cp38m-macosx_10_9_x86_64.whl -> cp38-cp38m-macosx_10_6_intel.whl
# - cp37-cp37m-macosx_10_9_x86_64.whl -> cp37-cp37m-macosx_10_6_intel.whl
# - cp36-cp36m-macosx_10_9_x86_64.whl -> cp36-cp36m-macosx_10_6_intel.whl

git:

    depth: False

matrix:

  include:

    - name: CPython 3.8.1 on Ubuntu 16.04 (Xenial Xerus)
      language: python
      os: linux
      dist: xenial
      python: 3.8.1
      before_install:
        - sudo apt-get install -y patchelf

    - name: CPython 3.7.3 on Ubuntu 16.04 (Xenial Xerus)
      language: python
      os: linux
      dist: xenial
      python: 3.7.3
      before_install:
        - sudo apt-get install -y patchelf

    - name: CPython 3.6.8 on Ubuntu 16.04 (Xenial Xerus)
      language: python
      os: linux
      dist: xenial
      python: 3.6.8
      before_install:
        - sudo apt-get install -y patchelf

    - name: CPython 3.8.1 on Windows 10 (64-bit)
      language: shell
      os: windows
      before_install:
        - export PATH=/c/Python38:/c/Python38/Scripts:$PATH
        - choco install python --version 3.8.1

    - name: CPython 3.7.3 on Windows 10 (64-bit)
      language: shell
      os: windows
      before_install:
        - export PATH=/c/Python37:/c/Python37/Scripts:$PATH
        - choco install python --version 3.7.3

    - name: CPython 3.6.8 on Windows 10 (64-bit)
      language: shell
      os: windows
      before_install:
        - export PATH=/c/Python36:/c/Python36/Scripts:$PATH
        - choco install python --version 3.6.8

    - name: CPython 3.8.1 on Windows 10 (32-bit)
      language: shell
      os: windows
      before_install:
        - export PATH=/c/Python38:/c/Python38/Scripts:$PATH
        - choco install python --version 3.8.1 --x86

    - name: CPython 3.7.3 on Windows 10 (32-bit)
      language: shell
      os: windows
      before_install:
        - export PATH=/c/Python37:/c/Python37/Scripts:$PATH
        - choco install python --version 3.7.3 --x86

    - name: CPython 3.6.8 on Windows 10 (32-bit)
      language: shell
      os: windows
      before_install:
        - export PATH=/c/Python36:/c/Python36/Scripts:$PATH
        - choco install python --version 3.6.8 --x86

    - name: CPython 3.8.1 on macOS 10.14 (Mojave)
      language: shell
      os: osx
      osx_image: xcode10.2
      before_install:
        # Build using the ancient 10.9 SDK (Anaconda/Python.org compatibility):
        - export MACOSX_DEPLOYMENT_TARGET=10.9
        # Includes are broken on Mojave, so fix them here:
        - export CFLAGS="-I$(xcrun --show-sdk-path)/usr/include"
        - export PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.8.1
        - travis_wait brew upgrade pyenv && pyenv install $PYENV_VERSION

    - name: CPython 3.7.3 on macOS 10.14 (Mojave)
      language: shell
      os: osx
      osx_image: xcode10.2
      before_install:
        # Build using the ancient 10.9 SDK (Anaconda/Python.org compatibility):
        - export MACOSX_DEPLOYMENT_TARGET=10.9
        # Includes are broken on Mojave, so fix them here:
        - export CFLAGS="-I$(xcrun --show-sdk-path)/usr/include"
        - export PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.7.3
        - pyenv install $PYENV_VERSION

    - name: CPython 3.6.8 on macOS 10.14 (Mojave)
      language: shell
      os: osx
      osx_image: xcode10.2
      before_install:
        # Build using the ancient 10.9 SDK (Anaconda/Python.org compatibility):
        - export MACOSX_DEPLOYMENT_TARGET=10.9
        # Includes are broken on Mojave, so fix them here:
        - export CFLAGS="-I$(xcrun --show-sdk-path)/usr/include"
        - export PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.6.8
        - pyenv install $PYENV_VERSION

env:
  global:
    - TWINE_USERNAME=brandtbucher
    - secure: "O01Wfk/mDdmH+mXFabZwIUBrriduFZlfMCnCEOTVxiSSO3tct8mbtVThjp4XQINI2fMvZ3xcwyXyNNGqkseZYFN0J9ks9IP+J/2Rq79WKf9WQSMJAWhkEwoDQ9jVZq6biGkuJas/XJtixC/AXuNyXyt5HeTma9y4RuaOZNO9rqBdEocspaS+rij0cevW7dqN1WPzMxq2cNxa7Gh55BbLTXF9aiHBEsUX55nHsn5wbDnaNI0IvgweXNjF0cj8+bRQnRO1CP+U0U9D4XjPhesrfk9clavz5S7z9C1cW3EhkpDKoEv6HeLC4mAZpBhlmilSxObCalj3IFqg3pdXSl+7PGbgVeAzZvzhuU8VfZ9/IynMb/9rqL79BJP1xLW4PQbtSSyIxJ8DU2bMDp0NvA35Sa1e+ScVSOad+nB3Nghd34puAdXVYsUIMNL/4k4yTlgIBkLretwnTF7qgml7ZYPceYEyDYw6riRXKmv0cyKSREz/Coz0HFmKwY3JHM85Fg8NidsrI+HETGJAk6DLGwHbZJGBOhm9UUlFRYd+WEq7PmJ2CouNRcpFfJiALstt+wXW1ybWA42kWKYEL40nEilm5f1wL3H+ZDDWQ+ZUvg0ArdWeXInGJwJ7tmk2PpdDbukPsMJBui9m667DJ07i/giXwgkIsaGzZha5RZML8tth0q0="

# Needed for Windows. Remove once Travis fixes this (or pypi deploy works):
# https://travis-ci.community/t/current-known-issues-please-read-this-before-posting-a-new-topic/264/10
# Not a dealbreaker, since secrets are disabled on forks/PRs. Just nice to have.
filter_secrets: false

install: pip install -r requirements.txt

script: invoke test

deploy:
  # The "pypi" provider breaks on Windows right now, so we need to use "script":
  # https://github.com/travis-ci/dpl/issues/955
  provider: script
  skip_cleanup: true
  script: twine upload --skip-existing dist/*
  on:
    repo: brandtbucher/automap
    tags: true
