on: [pull_request, push]
jobs:
  build_sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - run: python setup.py sdist
      - uses: actions/upload-artifact@v2
        with:
          path: dist/*.tar.gz
  build_wheels:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - run: python -m pip install cibuildwheel==1.6.1
      - run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BEFORE_TEST: python -m pip install -r {project}/requirements.txt
          CIBW_BUILD: cp36-* cp37-* cp38-*
          CIBW_TEST_COMMAND: pytest {project}
      - uses: actions/upload-artifact@v2
        with:
          path: wheelhouse/*.whl
