on: [pull_request, push]
jobs:
  build_sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: python setup.py sdist
      - uses: actions/upload-artifact@v2
        with:
          path: dist/*
  build_wheels:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install cibuildwheel
      - run: cibuildwheel
        env:
          CIBW_BUILD: cp36-* cp37-* cp38-*
          CIBW_BEFORE_TEST: pip install -r {project}/requirements.txt
          CIBW_TEST_COMMAND: pytest {project}
      - uses: actions/upload-artifact@v2
        with:
          path: wheelhouse/*
