on:
  pull_request:
  push:
  release:
    types: [published]
jobs:
  build_source:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - uses: actions/setup-python
      - run: python setup.py sdist
      - uses: actions/upload-artifact
        with:
          name: dist
          path: dist
  build_and_test_wheels:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        build: [cp36-*, cp37-*, cp38-*]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout
      - uses: actions/setup-python
      - run: pip install cibuildwheel
      - run: cibuildwheel --output-dir dist
        env:
          CIBW_BUILD: ${{ matrix.build }}
          CIBW_BEFORE_TEST: pip install -r {project}/requirements.txt
          CIBW_TEST_COMMAND: pytest {project}
      - uses: actions/upload-artifact
        with:
          name: dist
          path: dist
  publish_release:
    if: github.event_name == 'release' && github.event.action == 'published'
    needs: [build_source, build_and_test_wheels]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact
        with:
          name: dist
          path: dist
      - uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_TOKEN }}
          skip_existing: true
