name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  release:
    types: published

jobs:
  tar_gz:
    name: Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - run: python setup.py sdist
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  whl_lt_3_9:
    name: Build / ${{ matrix.os }} / Python 3.${{ matrix.minor }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS, Ubuntu, Windows]
        minor: [7, 8]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pypa/cibuildwheel@v2.11.2
        with:
          output-dir: dist
        env:
          CIBW_BUILD: cp3${{ matrix.minor }}-*
          CIBW_ARCHS_MACOS: all
          CIBW_BEFORE_BUILD: pip install -r {project}/requirements-build-backward.txt
          CIBW_BEFORE_TEST: pip install -r {project}/requirements-backward.txt
          CIBW_TEST_COMMAND: pytest {project}

      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  whl_gte_3_9:
    name: Build / ${{ matrix.os }} / Python 3.${{ matrix.minor }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS, Ubuntu, Windows]
        minor: [9, 10, 11]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pypa/cibuildwheel@v2.11.2
        with:
          output-dir: dist
        env:
          CIBW_BUILD: cp3${{ matrix.minor }}-*
          CIBW_ARCHS_MACOS: all
          CIBW_BEFORE_BUILD: pip install -r {project}/requirements-build.txt
          CIBW_BEFORE_TEST: pip install -r {project}/requirements.txt
          CIBW_TEST_COMMAND: pytest {project}

      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  upload:
    name: Publish
    if: github.event_name == 'release' && github.event.action == 'published'
    needs: [tar_gz, whl_lt_3_9, whl_gte_3_9]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          password: ${{ secrets.PYPI_TOKEN }}
          skip_existing: true
