on:
  pull_request:
  push:
  release:
    types: [published]
jobs:
  build_source:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: python setup.py sdist
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/*
  build_wheels:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install cibuildwheel
      - run: cibuildwheel
        env:
          CIBW_BUILD: cp36-* cp37-* cp38-*
          CIBW_BEFORE_TEST: pip install -r {project}/requirements.txt
          CIBW_TEST_COMMAND: pytest {project}
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: wheelhouse/*
  upload_pypi:
    needs: [build_source, build_wheels]
    runs-on: ubuntu-latest
    # if: github.event_name == "release" && github.event.action == "published"
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_TOKEN }}
          repository_url: https://test.pypi.org/legacy
