name: CI
on:
  pull_request:
  push:
  release:
    types: published
jobs:
  tar_gz:
    name: Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: python setup.py sdist
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
  whl:
    name: Build / ${{ matrix.os }} / Python 3.${{ matrix.minor }}
    strategy:
      matrix:
        os: [macOS, Ubuntu, Windows]
        minor: [6, 7, 8, 9]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: docker/setup-qemu-action@v1
        if: runner.os == 'Linux'
        with:
          platforms: all
      - uses: joerick/cibuildwheel@v1.9.0
        with:
          output-dir: dist
        env:
          CIBW_ARCHS: all
          CIBW_BUILD: cp3${{ matrix.minor }}-*
          CIBW_BEFORE_TEST: pip install -r {project}/requirements.txt
          CIBW_TEST_COMMAND: pytest {project}
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
  upload:
    name: Publish
    if: github.event_name == 'release' && github.event.action == 'published'
    needs: [tar_gz, whl]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          password: ${{ secrets.PYPI_TOKEN }}
          skip_existing: true
